DISABLE_IMPLICIT_BINDINGS: true
ENABLE_COMPILER_OPTIONS: false
ALLOW_ENABLE_NETWORK: false
CPU_TIME_LIMIT: 10
CPU_EXTRA_TIME: 5
WALL_TIME_LIMIT: 20
MEMORY_LIMIT: 131072
MAX_PROCESSES_AND_OR_THREADS: 30
MAX_FILE_SIZE: 1024
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT: false
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT: false
